SELECT DISTINCT
  res.Id_PersonaComunicar,
  res.perfil,
  res.Horario_Contacto,
  res.aviso_privacidad,
  res.comunicacion_whatsapp,
  res.Estudiante_Id,
  res.Estudiante_FirstName,
  res.Estudiante_ApellidoPaterno,
  res.Estudiante_ApellidoMaterno,
  res.Estudiante_FechaNacimiento_Formatted,
  res.Estudiante_Email,
  res.Estudiante_Phone,
  res.Estudiante_Locale,
  res.periodo_de_interes_pivote,
  res.programa_de_interes_pivote,
  res.campus_de_interes_pivote,
  res.utm_campaign,
  res.utm_source,
  res.utm_term,
  res.utm_content,
  res.adm_url_landing__c,
  res.business_unit__pivote_,
  res.adm_wl_clave_origen__c,
  res.adm_wl_clave_estatus__c,
  res.adm_sistema_origen__c,
  res.adm_modalidad__c,
  res.adm_wl_clave_nivel__c,
  res.Origen,
  res.Submit_Date,
  res.Estudiante_FechaNacimiento,
  res.Validado,
  res.Estudiante_SexoLegal,
  res.calificacionExperiencia,
  res.Estudiante_CodePhone,
  res.area_de_interes_pivote,
  res.Flag,
  res.Phone_PersonaComunicar,
  res.Locale_PersonaComunicar,
  res.OptOutStatusID,
  res.utm_cve_periodo_iniciativa,
  res.utm_medium,
  res.utm_cve_sede_iniciativa,
  res.Validated_date,
  res.Medio,
  res.IsTest,
  res.Lead_Id,
  res.Canal,
  res.periodo_futuro,
  res.a_os_graduacion,
  res.Universidad_Graduacion,
  res.nivel_de_ingles,
  res.Programa_ClaveBanner,
  res.Periodo_Clave,
  res.Sede_Clave,
  res.Agrupacion_Clave,
    CONCAT('https://egade-admisiones.tec.mx/1gf1pkjcghq?MC_Id=',res.Id_PersonaComunicar) AS URL_Call_Center,
  0 AS Task_created
FROM Respuestas_Formularios_EGADE1 res
    LEFT JOIN Callcenter_Formularios_Tec_Mx cc
        ON cc.Id_PersonaComunicar = res.Id_PersonaComunicar
WHERE  res.Validado = 'Call Center'
AND (res.adm_url_landing__c NOT LIKE '%https://egade-admisiones.tec.mx/ee-%'
  OR res.adm_url_landing__c IS NULL 
     OR res.adm_url_landing__c = '')